### ISSUE TITLE
stageview is blank/not rendering

### ISSUE THREAD

**Issue by uncojohnco** [uncojohnco/usd-sandbox#13]
When using usdview for the first time the stageView is black i.e not rendering(?)

 might be because I'm using a VM...

```
usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda
```

```python
Traceback (most recent call last):
  File "/usr/local/USD/lib/python/pxr/Usdviewq/stageView.py", line 1559, in paintGL
    GL.glEnable(GL_FRAMEBUFFER_SRGB_EXT)
  File "/home/usd/.local/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/usd/.local/lib/python2.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1280,
        description = 'invalid enumerant',
        baseOperation = glEnable,
        cArguments = (GL_FRAMEBUFFER_SRGB_EXT,)
```

**Comment by uncojohnco** [comment]
Also when picking in the stageview...

```python
```cpp
ERROR: Usdview encountered an error while picking.
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at line 80 in file /home/usd/git/USD/pxr/imaging/lib/glf/diagnostic.cpp : 'GL error: invalid framebuffer operation, reported from bool pxrInternal_v0_19__pxrReserved__::UsdImagingGLLegacyEngine::TestIntersection(const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::UsdPrim&, const pxrInternal_v0_19__pxrReserved__::UsdImagingGLRenderParams&, pxrInternal_v0_19__pxrReserved__::GfVec3d*, pxrInternal_v0_19__pxrReserved__::SdfPath*, pxrInternal_v0_19__pxrReserved__::SdfPath*, int*, int*)'
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at line 80 in file /home/usd/git/USD/pxr/imaging/lib/glf/diagnostic.cpp : 'GL error: invalid framebuffer operation, reported from bool pxrInternal_v0_19__pxrReserved__::UsdImagingGLLegacyEngine::TestIntersection(const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::UsdPrim&, const pxrInternal_v0_19__pxrReserved__::UsdImagingGLRenderParams&, pxrInternal_v0_19__pxrReserved__::GfVec3d*, pxrInternal_v0_19__pxrReserved__::SdfPath*, pxrInternal_v0_19__pxrReserved__::SdfPath*, int*, int*)'
        Error in 'pxrInternal_v0_19__pxrReserved__::GlfPostPendingGLErrors' at line 80 in file /home/usd/git/USD/pxr/imaging/lib/glf/diagnostic.cpp : 'GL error: invalid value, reported from bool pxrInternal_v0_19__pxrReserved__::UsdImagingGLLegacyEngine::TestIntersection(const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::GfMatrix4d&, const pxrInternal_v0_19__pxrReserved__::UsdPrim&, const pxrInternal_v0_19__pxrReserved__::UsdImagingGLRenderParams&, pxrInternal_v0_19__pxrReserved__::GfVec3d*, pxrInternal_v0_19__pxrReserved__::SdfPath*, pxrInternal_v0_19__pxrReserved__::SdfPath*, int*, int*)'

**Comment by uncojohnco** [comment]
This is resolved, had to enable the nvidia video card on my laptop. I had it disabled to use the intel video card to save battery power :upside_down_face:
